feat: release build
* feat: adding release workflow
* docs: added java page
* fix: version was not present
* feat: added install script and improved ntabul
* release: added docker
* fix: local installation is now a jre one to test jlink distribution
* feat: added jre distribution for linux and alpine
* fix: jdk.dynalink missing - in doc-exec
* refactor: install-cli is now in ntabul
* fix: loglevel was set to info
* refactor: next tabul is the jre assembly

diff --git a/contrib/script/doc-exec b/contrib/script/doc-exec
--- a/contrib/script/doc-exec
+++ b/contrib/script/doc-exec
@@ -3,6 +3,10 @@
 
 set -TCEeuo pipefail
 
+# Reset
+NC='\033[0m'     # No Color
+RED='\033[0;31m' # Red
+
 find_git_root() {
   local dir="$PWD"
   while [[ "$dir" != "/" ]]; do
@@ -26,7 +30,7 @@ if [ "$#" -lt 1 ]; then
   echo "  * --compile     : recompile the whole project"
   echo "  * --resume      : don't delete the environment (ie sqlite, ...)"
   echo "  * --install-cli : install the cli before running"
-  echo "  * --ide         : runs the Tabul.class instead of the tabul cli (way quicker as it stay in the same jvm)"
+  #echo "  * --ide         : runs the Tabul.class instead of the tabul cli (way quicker as it stay in the same jvm)"
   echo "  * --no-cache    : suppress the cache for the selected pages"
   echo "  * --purge-cache : suppress the whole cache directory"
   echo "  * globPath      : a glob path."
@@ -40,7 +44,7 @@ MAVEN_COMPILE=false
 # Install the cli before running?
 INSTALL_CLI=false
 # Run with the ide and not the cli?
-IDE_RUN=false
+# IDE_RUN=false
 # Doc exec options
 DOC_EXEC_OPTIONS=()
 while [ $# -gt 0 ]; do
@@ -52,10 +56,10 @@ while [ $# -gt 0 ]; do
     --install-cli)
       INSTALL_CLI=true
       ;;
-    --ide)
-      IDE_RUN=true
-      DOC_EXEC_OPTIONS+=("$1")
-      ;;
+      #    --ide)
+      #      IDE_RUN=true
+      #      DOC_EXEC_OPTIONS+=("$1")
+      #      ;;
     *)
       DOC_EXEC_OPTIONS+=("$1")
       ;;
@@ -65,7 +69,11 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-PROJECT_ROOT=$(find_git_root)
+# Set by envrc normally
+if [ "$PROJECT_ROOT" == "" ]; then
+  PROJECT_ROOT=$(find_git_root)
+fi
+
 TABULIFY_CLI_DIR="$PROJECT_ROOT/cli-tabul"
 cd "$TABULIFY_CLI_DIR"
 
@@ -80,28 +88,44 @@ if [ "$MAVEN_COMPILE" == "true" ]; then
     exit 1
   fi
   # Compile the project using Maven (The DocRun class is in test)
-  if ! OUTPUT=$(mvn test-compile); then
-    echo "Maven build failed."
-    echo "$OUTPUT"
-    exit 1
-  fi
+  #if ! OUTPUT=$(mvn test-compile); then
+  #  echo "Maven build failed."
+  #  echo "$OUTPUT"
+  #  exit 1
+  #fi
 fi
 
 export TABUL_EXEC_ENV="dev"
-if [ "$IDE_RUN" == "true" ]; then
-  # When the code run as ide, tabul does not exit, it will throw
-  # otherwise the doc executor security manager see it as executing and to prevent exit will throw
-  TABUL_EXEC_ENV="ide"
-  export TABUL_HOME="$PROJECT_ROOT"
-fi
+#if [ "$IDE_RUN" == "true" ]; then
+#  # When the code run as ide, tabul does not exit, it will throw
+#  # otherwise the doc executor security manager see it as executing and to prevent exit will throw
+#  TABUL_EXEC_ENV="ide"
+#  export TABUL_HOME="$PROJECT_ROOT"
+#fi
 
+CLI_PROJECT="cli-tabul"
 # Install the cli before executing
 if [ "$INSTALL_CLI" == "true" ]; then
-  if ! install-cli; then
-    echo "Install cli failed"
+  echo "Assembling Tabul"
+  if ! mvnw jreleaser:assemble -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Djreleaser.config.file="$JRELEASER_FILE" -pl "$CLI_PROJECT"; then
+    echo -e "${RED}Assembling Error: check the logs at $JRELEASER_LOG${NC}"
     exit 1
   fi
 fi
+
+# Tabul home is important because it will be seen in the doc
+# /opt/tabulify to have short path for the resource connection
+# example for the howto: file:///opt/tabulify/resources/howto/
+TABUL_HOME=${CLI_TABUL_HOME:-/opt/tabulify}
+
+if [ ! -f "$TABUL_HOME/bin/tabul" ]; then
+  echo -e "${RED}tabul was not found at $TABUL_HOME/bin/tabul${NC}"
+  echo -e "${RED}install it with \`ntabul --install\`${NC}"
+  exit 1
+fi
+
+export PATH="$TABUL_HOME/bin:$PATH"
+
 # no warning in doc
 export TABUL_LOG_LEVEL=error
 # Trick to have a USER_HOME consistent in the doc
@@ -110,11 +134,15 @@ export TABUL_OS_USER_HOME=/home/tabulify
 cd "$TABUL_OS_USER_HOME"
 
 PATH_DOC="$PROJECT_ROOT/docs-tabul/data/pages"
-PATH_INLINE_FILE="/opt/tabulify/resources/howto"
+PATH_INLINE_FILE="$TABUL_HOME/resources/howto"
 
-/opt/doc-exec/bin/doc-exec --doc-path "$PATH_DOC" --file-path ${PATH_INLINE_FILE} --doc-name "tabulify" "${DOC_EXEC_OPTIONS[@]}"
+# It's a wrapper script, we select the second in path order
+# this one is the first, the second is brew
+if ! "$(which -a doc-exec | sed -n '2p')" --doc-path "$PATH_DOC" --file-path "${PATH_INLINE_FILE}" --doc-name "tabulify" "${DOC_EXEC_OPTIONS[@]}"; then
+  echo -e "${RED}Error were seen while executing the doc${NC}"
+  exit 1
+fi
 
-exit
 # Deprecated Old
 ## Exec
 #MAIN_CLASS=com.tabulify.doc.DocExec
diff --git a/contrib/script/ntabul b/contrib/script/ntabul
--- a/contrib/script/ntabul
+++ b/contrib/script/ntabul
@@ -1,9 +1,23 @@
 #!/bin/bash
 # Next Tabul: The next version of tabul
-# Shortcut to run the tabul development version quickly after changing a class
-# It will recompile optionally and run tabul without the need to create a jar
 
 set -TCEeuo pipefail
+
+function synopsis() {
+  cat << EOF
+
+  ntabul : Next tabul, run the next tabul version
+
+      $(basename "$0") [options]
+
+  Options:
+    * -j | --java      : run the next java version (by default, it runs the distribution)
+    * -i | --install   : install:
+        * the distribution (distribution run)
+        * or the jars (java run)
+
+EOF
+}
 
 find_git_root() {
   local dir="$SCRIPT_DIR"
@@ -18,13 +32,19 @@ find_git_root() {
   return 1
 }
 
-MAVEN_COMPILE=false
+INSTALL=false
 TABUL_OPTIONS=()
+NEXT_TABUL_TYPE_DISTRIBUTION="distribution"
+NEXT_TABUL_TYPE_JAVA="java"
+NEXT_TABUL_TYPE=$NEXT_TABUL_TYPE_DISTRIBUTION
 while [ $# -gt 0 ]; do
 
   case "$1" in
-    --compile)
-      MAVEN_COMPILE=true
+    -i | --install)
+      INSTALL=true
+      ;;
+    -j | --java)
+      NEXT_TABUL_TYPE="$NEXT_TABUL_TYPE_JAVA"
       ;;
     *)
       TABUL_OPTIONS+=("$1")
@@ -35,36 +55,64 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-echo "Running Tabul with Java and Mvn classpath" > /dev/stderr
-
 if [ "$PROJECT_ROOT" == "" ]; then
   SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
   PROJECT_ROOT=$(find_git_root)
 fi
-cd "$PROJECT_ROOT/cli-tabul"
 
-# Extract main class from arguments
+# Tabul home is important because it will be seen in the doc
+# /opt/tabulify to have short path for the resource connection
+# example for the howto: file:///opt/tabulify/resources/howto/
+TABUL_HOME=${CLI_TABUL_HOME:-/opt/tabulify}
+
+if [ "$NEXT_TABUL_TYPE" == "$NEXT_TABUL_TYPE_DISTRIBUTION" ]; then
+  # Distribution installation
+
+  if [ $INSTALL == true ]; then
+    echo "Install distribution"
+    install
+    echo "Install distribution done"
+  else
+    if [ ! -f "$TABUL_HOME/bin/tabul" ]; then
+      echo "Tabul assembly not found, installing" > /dev/stderr
+      install
+    fi
+  fi
+  echo "Running tabul in $TABUL_HOME" > /dev/stderr
+  if ! "${TABUL_HOME}/bin/tabul" "${TABUL_OPTIONS[@]}"; then
+    echo -e "${RED}Error while running tabul in TABUL_HOME${NC}" > /dev/stderr
+    exit 1
+  fi
+  exit
+fi
+
+echo "Running Tabul with Java (and Mvn classpath)" > /dev/stderr
+
+CLI_PROJECT="cli-tabul"
+
+# Main class
 MAIN_CLASS=com.tabulify.tabul.Tabul
 
 # Dependency
-CLASSPATH=$(mvn dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q)
+CLASSPATH=$(mvn dependency:build-classpath -pl "$CLI_PROJECT" -Dmdep.outputFile=/dev/stdout -q)
 
 # Add the target/classes directory to include your compiled classes
-CLASSPATH="$CLASSPATH:target/classes"
+CLASSPATH="$CLASSPATH:$PROJECT_ROOT/$CLI_PROJECT/target/classes"
 
-if [ "$MAVEN_COMPILE" == "true" ]; then
-  echo "Building project with Maven..."
+if [ $INSTALL == true ]; then
+  echo "Installing jars with Maven..."
   if ! OUTPUT=$(
     cd "$PROJECT_ROOT"
     mvn install -DskipTests
   ); then
     echo "$OUTPUT"
-    echo "Maven Project build failed."
+    echo "Maven Project install failed."
     exit 1
   fi
 fi
 
-command="TABUL_ENV=ide java -cp \"$CLASSPATH\" \"$MAIN_CLASS\" ${TABUL_OPTIONS[*]}"
+# to get the stack, add TABUL_EXEC_ENV=ide
+command="java -cp \"$CLASSPATH\" \"$MAIN_CLASS\" ${TABUL_OPTIONS[*]}"
 eval "$command"
 
 # Note: exec:java does not work, as it does not add the resources
diff --git a/contrib/script/release b/contrib/script/release
--- a/contrib/script/release
+++ b/contrib/script/release
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
-# Release of the cli
+# Local Release of the cli
+# Superseded by the github workflow release
+# but is still used for release development and local installation
 set -TCEeuo pipefail
 
 # Reset
@@ -17,11 +19,12 @@ function synopsis() {
       $(basename "$0") [options] [patch|minor|major|none]
 
   Options:
-    * -a | --assemble-only    : create the archive only (will not release)
-    * -c | --config-only      : create the config only (will not release)
-    * -l | --changelog-only   : create the changelog only (will not release)
-    * -p | --prepare-only     : create the archive and the packagers manifest only (will not release)
-    * -na | --no-assembly     : no assembly is performed
+    * -a | --assemble-only     : create the archive only (will not release)
+    * -c | --config-only       : create the config only (will not release)
+    * -l | --changelog-only    : create the changelog only (will not release)
+    * -p | --prepare-only      : create the archive and the packagers manifest only (will not release)
+    * -na | --no-assembly      : no assembly is performed
+    * -cp | --current-platform : assemble only for the current platform (no by default)
     * --debug                 : set the level to debug
   Args:
     * patch|minor|major|early : is the type of bump for the semver version (default to early - no bump)
@@ -38,11 +41,15 @@ PREPARE_GOAL="prepare"
 CONFIG_GOAL="config"
 CHANGELOG_GOAL="changelog"
 ASSEMBLY=true
+CURRENT_PLATFORM=false
 LEVEL=warn # The org.slf4j.simpleLogger.defaultLogLevel value
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    -a | --assemble-only)
+    -a | --assembly-only)
       GOAL="$ASSEMBLE_GOAL"
+      ;;
+    -cp | --current-platform)
+      CURRENT_PLATFORM=true
       ;;
     -c | --config-only)
       GOAL="$CONFIG_GOAL"
@@ -96,9 +103,6 @@ if [[ "$RELEASE_VERSION" =~ .*-SNAPSHOT ]]; then
   EFFECTIVE_VERSION="early-access"
 fi
 
-
-
-
 # Common Arg
 # Because we call only the cli module, jreleaser is expected to be in this directory
 JRELEASER_FILE="jreleaser.yml"
@@ -133,27 +137,42 @@ if [ $ASSEMBLY == true ]; then
   mvnw install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=$LEVEL # create the lib and cli archive
   echo "Copying dependencies $RELEASE_VERSION"
   mvnw -Pdeps -pl "$PROJECT_TO_RELEASE" -Dorg.slf4j.simpleLogger.defaultLogLevel=$LEVEL
-  echo "Downloading Jdk $RELEASE_VERSION"
-  if ! mvnw -Pjdks -pl "$PROJECT_TO_RELEASE" -Dorg.slf4j.simpleLogger.defaultLogLevel=$LEVEL; then
-    echo -e "${RED}Error: while downloading the JDK check the logs at $JRELEASER_LOG${NC}"
-    exit 1
+  echo "Downloading and extracting Jdk $RELEASE_VERSION"
+  # Jdks still extract and we get a bunch of warnings
+  # We set the archiver log to error to avoid a bunch of warning
+  # See https://github.com/jreleaser/jreleaser/issues/2028
+  if [ ! -d /tmp/jdks ]; then
+    if ! mvnw -Pjdks -pl "$PROJECT_TO_RELEASE" -Dorg.slf4j.simpleLogger.log.org.codehaus.plexus.archiver.tar.TarGZipUnArchiver=error -Dorg.slf4j.simpleLogger.defaultLogLevel=$LEVEL; then
+      echo -e "${RED}Error: while downloading the JDK check the logs at $JRELEASER_LOG${NC}"
+      exit 1
+    fi
+    echo "Downloading Jdk Done"
+  else
+    # to avoid extraction
+    echo "Downloading Jdk Skipped. Jdks directory exists"
   fi
-  echo "Downloading Jdk Done"
+
   echo "Assembling version $RELEASE_VERSION"
-  if ! mvnw jreleaser:assemble -Dorg.slf4j.simpleLogger.defaultLogLevel=$LEVEL "${JRELEASER_COMMON_ARGS[@]}"; then
-    echo -e "${RED}Error: check the logs at $JRELEASER_LOG${NC}"
+  ASSEMBLY_ARGS=(-Dorg.slf4j.simpleLogger.defaultLogLevel="$LEVEL")
+  if [ $CURRENT_PLATFORM == true ]; then
+    # Current platform doc: https://jreleaser.org/guide/latest/tools/jreleaser-maven.html#_filtering_artifacts
+    ASSEMBLY_ARGS+=(-Djreleaser.select.current.platform)
+  fi
+  if ! mvnw jreleaser:assemble "${ASSEMBLY_ARGS[@]}" "${JRELEASER_COMMON_ARGS[@]}"; then
+    echo -e "${RED}Assembly Error: check the logs at $JRELEASER_LOG${NC}"
     exit 1
   fi
   echo "Assembling $RELEASE_VERSION done"
 
   echo "Testing Assembly $RELEASE_VERSION"
   TABUL_BIN="$PROJECT_ROOT/$PROJECT_TO_RELEASE/target/jreleaser/assemble/tabulify-nojre/java-archive/work/tabulify-$EFFECTIVE_VERSION-nojre/bin/tabul"
-  if ! $TABUL_BIN version; then
+  if ! $TABUL_BIN version > /dev/null; then
     echo -e "${RED}Error: assembly error${NC}"
     echo -e "${RED}The executable returns an error: $TABUL_BIN${NC}"
     exit 1
   fi
   echo "Test successful"
+  echo "Assembly done"
 else
   echo "Assembly disabled"
 fi
diff --git a/contrib/script/release-tag b/contrib/script/release-tag
--- a/contrib/script/release-tag
+++ b/contrib/script/release-tag
@@ -1,27 +1,75 @@
 #!/usr/bin/env bash
 # Create a tag
 
+NC='\033[0m'     # No Color
+RED='\033[0;31m' # Red
+
+function synopsis() {
+  cat << EOF
+
+  Release Tag:
+
+      $(basename "$0") [options] [patch|minor|major|none]
+
+  Args:
+    * patch|minor|major|none : is the type of bump for the semver version (default to none - no bump)
+
+  The version is changed if the bump type is patch|minor|major
+
+EOF
+}
+
+NO_BUMP_TYPE="none"
+BUMP_TYPE="$NO_BUMP_TYPE"
 if [ -z "$1" ]; then
-	echo "Please provide a tag."
-	echo "Usage: ./release-tag v[X.Y.Z]"
-	exit
+  echo -e "${RED}Please provide a bump type.${NC}"
+  synopsis
+  exit
 fi
 
-tag_name=$1;
+echo "Determining the version"
+if [ "$BUMP_TYPE" != "$NO_BUMP_TYPE" ]; then
+  echo "Version bump asked"
+  # Get the next version
+  export GIT_CLIFF__BUMP__INITIAL_TAG=v0.1.0 # by default it's 0.1.0
+  if ! RELEASE_VERSION=$(git cliff --unreleased --context --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" --ignore-tags "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]*" --bump "$BUMP_TYPE" | jq -r '.[0].version' | tr -d "v"); then
+    echo -e "${RED}Error while getting the next version${NC}"
+  fi
+  # Jreleaser read the version from the pom file
+  # We need to modify the pom file
+  echo "Creating Next version $RELEASE_VERSION commit"
+  mvnw versions:set -DgenerateBackupPoms=false -DnewVersion="$RELEASE_VERSION"
+  git commit -am "chore(release): $RELEASE_VERSION"
+  git push origin
+  echo "Next version $RELEASE_VERSION commit done"
+else
+  echo "No bump taking the actual version"
+  RELEASE_VERSION=$(yq '.project.version' pom.xml)
+fi
+echo "Version determined to be $RELEASE_VERSION"
+
+echo "Determining the tag"
+if [[ "$RELEASE_VERSION" =~ .*-SNAPSHOT ]]; then
+  TAG_NAME="early-access"
+else
+  TAG_NAME="v$RELEASE_VERSION"
+fi
+echo "Tag determined to be $TAG_NAME"
 
 # Delete the tag if it exists (both locally and remotely)
-if git tag -l | grep -q "^${tag_name}$"; then
-    echo "Deleting existing local tag: $tag_name"
-    git tag -d "$tag_name"
+if git tag -l | grep -q "^${TAG_NAME}$"; then
+  echo "Deleting existing local tag: $TAG_NAME"
+  git tag -d "$TAG_NAME"
 fi
 
 # Check if tag exists on remote and delete it
-if git ls-remote --tags origin | grep -q "refs/tags/${tag_name}$"; then
-    echo "Deleting existing remote tag: $tag_name"
-    git push origin --delete "$tag_name"
+if git ls-remote --tags origin | grep -q "refs/tags/${TAG_NAME}$"; then
+  echo "Deleting existing remote tag: $TAG_NAME"
+  git push origin --delete "$TAG_NAME"
 fi
 
 echo "Creating Tag $1"
 git tag "$1"
 echo "Pushing Tag $1"
 git push origin tag "$1"
+echo "Tagging done. Exiting"
